/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ConversationTurn = IDL.Record({
  'question' : IDL.Text,
  'timestamp' : IDL.Int,
  'aiResponse' : IDL.Text,
});
export const DocumentMetadata = IDL.Record({
  'name' : IDL.Text,
  'extractedText' : IDL.Text,
  'uploadDate' : IDL.Int,
});
export const PracticeRecord = IDL.Record({
  'topic' : IDL.Text,
  'attempts' : IDL.Nat,
  'score' : IDL.Nat,
  'lastAttempt' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'trialExpired' : IDL.Bool,
  'trialStarted' : IDL.Int,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'subscriptionActive' : IDL.Bool,
});
export const ConversationHistory = IDL.Record({
  'turns' : IDL.Vec(ConversationTurn),
  'lastActivity' : IDL.Int,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addConversationTurn' : IDL.Func([ConversationTurn], [], []),
  'addExtractedDoc' : IDL.Func([DocumentMetadata], [], []),
  'addPracticeRecord' : IDL.Func([PracticeRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkTrialStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'clearConversationHistory' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationHistory' : IDL.Func(
      [],
      [IDL.Opt(ConversationHistory)],
      ['query'],
    ),
  'getPracticeRecords' : IDL.Func([], [IDL.Vec(PracticeRecord)], ['query']),
  'getStudyMaterials' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getWeakTopics' : IDL.Func([], [IDL.Vec(PracticeRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeStudyMaterial' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'startFreeTrial' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ConversationTurn = IDL.Record({
    'question' : IDL.Text,
    'timestamp' : IDL.Int,
    'aiResponse' : IDL.Text,
  });
  const DocumentMetadata = IDL.Record({
    'name' : IDL.Text,
    'extractedText' : IDL.Text,
    'uploadDate' : IDL.Int,
  });
  const PracticeRecord = IDL.Record({
    'topic' : IDL.Text,
    'attempts' : IDL.Nat,
    'score' : IDL.Nat,
    'lastAttempt' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'trialExpired' : IDL.Bool,
    'trialStarted' : IDL.Int,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'subscriptionActive' : IDL.Bool,
  });
  const ConversationHistory = IDL.Record({
    'turns' : IDL.Vec(ConversationTurn),
    'lastActivity' : IDL.Int,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addConversationTurn' : IDL.Func([ConversationTurn], [], []),
    'addExtractedDoc' : IDL.Func([DocumentMetadata], [], []),
    'addPracticeRecord' : IDL.Func([PracticeRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkTrialStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'clearConversationHistory' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationHistory' : IDL.Func(
        [],
        [IDL.Opt(ConversationHistory)],
        ['query'],
      ),
    'getPracticeRecords' : IDL.Func([], [IDL.Vec(PracticeRecord)], ['query']),
    'getStudyMaterials' : IDL.Func([], [IDL.Vec(DocumentMetadata)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getWeakTopics' : IDL.Func([], [IDL.Vec(PracticeRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeStudyMaterial' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'startFreeTrial' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };