/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationHistory {
  'turns' : Array<ConversationTurn>,
  'lastActivity' : bigint,
  'createdAt' : bigint,
}
export interface ConversationTurn {
  'question' : string,
  'timestamp' : bigint,
  'aiResponse' : string,
}
export interface DocumentMetadata {
  'name' : string,
  'extractedText' : string,
  'uploadDate' : bigint,
}
export interface PracticeRecord {
  'topic' : string,
  'attempts' : bigint,
  'score' : bigint,
  'lastAttempt' : bigint,
}
export interface StudentProfile {
  'trialExpired' : boolean,
  'trialStarted' : bigint,
  'name' : string,
  'email' : string,
  'subscriptionActive' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addConversationTurn' : ActorMethod<[ConversationTurn], undefined>,
  'addExtractedDoc' : ActorMethod<[DocumentMetadata], undefined>,
  'addPracticeRecord' : ActorMethod<[PracticeRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkTrialStatus' : ActorMethod<[], boolean>,
  'clearConversationHistory' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationHistory' : ActorMethod<[], [] | [ConversationHistory]>,
  'getPracticeRecords' : ActorMethod<[], Array<PracticeRecord>>,
  'getStudyMaterials' : ActorMethod<[], Array<DocumentMetadata>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getWeakTopics' : ActorMethod<[], Array<PracticeRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeStudyMaterial' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'startFreeTrial' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];